frameworkVersion: '3'

# Removes serveless enterprise plugin injection
# See https://www.serverless.com/blog/framework-release-v138-websockets
# org: benoitmarchant
service: plum-apps-phront-desk

package:
    exclude:
      - ~/**
      - tools/**
      - .vscode/**
      - node_modules/montage/.git/**
      - node_modules/montage/demo/**
      - node_modules/montage/ui/**
      - node_modules/montage/test/**
      - node_modules/montage/testing/**
      - node_modules/montage/tools/**
      - node_modules/montage-geo/.git/**
      - node_modules/phront/.git/**
      - node_modules/phront/test/**
      - node_modules/phront/sandbox/**
      - node_modules/local-websocket-server/**
      - node_modules/serverless/**
      - node_modules/serverless-offline/**
      - node_modules/serverless-plugin-include-dependencies/**
  
#setup for environements and accounts to use so we cand do
# $ serverless deploy --stage mod
# $ serverless deploy --stage test
# $ serverless deploy --stage live
# more at https://serverless-stack.com/chapters/configure-multiple-aws-profiles.html
custom:
  myStage: ${opt:stage, self:provider.stage}
  myRegion: 
    mod: us-east-1
    test: us-west-2
    live: us-east-1
  myProfile:
    mod: cogent-mod
    test: cogent-test
    live: cogent-live
    s3Bucket: ${self:service}
  myAccount:
    mod: 006408448862
    test: 545740467277
    live: 540973189736

  s3Sync:
    # A simple configuration for copying static assets
    - bucketName: ${self:service} # required
      #bucketPrefix: assets/ # optional
      localDir: builds/phront-desk # required
      # localDir: / # required
      deleteRemoved: false # optional, indicates whether sync deletes files no longer present in localDir. Defaults to 'true'
      #acl: public-read # optional
      followSymlinks: true # optional
      #defaultContentType: text/html # optional
      params: # optional
        - index.html:
            CacheControl: 'public, must-revalidate, proxy-revalidate, max-age=0'
        - "*.js":
            CacheControl: 'public, max-age=31536000'
      #bucketTags: # optional, these are appended to existing S3 bucket tags (overwriting tags with the same key)
      #  tagKey1: tagValue1
      #  tagKey2: tagValue2

  prune:
    automatic: true
    includeLayers: true
    number: 3

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  profile: ${self:custom.myProfile.${self:custom.myStage}}
  role: arn:aws:iam::${self:custom.myAccount.${self:custom.myStage}}:role/lambda-runner 
  cfnRole: arn:aws:iam::${self:custom.myAccount.${self:custom.myStage}}:role/cloudformation-manager  # ARN of an IAM role for CloudFormation service. If specified, CloudFormation uses the role's credentials
  region: ${self:custom.myRegion.${self:custom.myStage}} # Overwrite the default region used. Default is us-east-1

resources:
  Resources:
    # AssetsBucket:
    #   Type: AWS::S3::Bucket
    #   Properties:
    #     BucketName: plum-appointments-${self:custom.myStage}

          
plugins:
  - serverless-s3-sync
  - serverless-scriptable-plugin
  #https://www.serverless.com/plugins/serverless-prune-plugin
  #https://github.com/claygregory/serverless-prune-plugin
  - serverless-prune-plugin
